import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Chatbot</Link>
        </li>
        <li>
          <Link to="/uiintro">UIIntro</Link>
        </li>
        <li>
          <Link to="/desktop">Desktop</Link>
        </li>
        <li>
          <Link to="/desktoptwo">DesktopTwo</Link>
        </li>
        <li>
          <Link to="/indexanasayfa">IndexAnasayfa</Link>
        </li>
        <li>
          <Link to="/kullanicigiris">Kullanicigiris</Link>
        </li>
        <li>
          <Link to="/kullanicikayit">KullaniciKayit</Link>
        </li>
        <li>
          <Link to="/desktopsix">DesktopSix</Link>
        </li>
        <li>
          <Link to="/sifresifirlama">Sifresifirlama</Link>
        </li>
        <li>
          <Link to="/desktopfour">DesktopFour</Link>
        </li>
        <li>
          <Link to="/desktopone">DesktopOne</Link>
        </li>
        <li>
          <Link to="/sifrekurtarmaonayi">Sifrekurtarmaonayi</Link>
        </li>
        <li>
          <Link to="/help">Help</Link>
        </li>
        <li>
          <Link to="/desktopfive">DesktopFive</Link>
        </li>
        <li>
          <Link to="/desktopseven">DesktopSeven</Link>
        </li>
        <li>
          <Link to="/customer">Customer</Link>
        </li>
        <li>
          <Link to="/desktopthree">DesktopThree</Link>
        </li>
        <li>
          <Link to="/desktopeight">DesktopEight</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
